sudo: false
language: ruby
os:
- linux
cache:
  bundler: true
  directories:
  - "$HOME/.cargo"
  - "$TRAVIS_BUILD_DIR/target"
rvm:
- 2.5.7
- 2.6.5
env:
  global:
  - NO_LINK_RUTIE=1
  - RUST_BACKTRACE=full
  - PATH=$PATH:$HOME/.cargo/bin
before_install:
- curl -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
- gem install bundler
matrix:
  include:
  - os: osx
    rvm: 2.5.5
  - os: osx
    rvm: 2.6.3
deploy:
  provider: releases
  api_key:
    secure: dH3MIhngZlZbSYZYYqZ8pkslLR6FxMFZKpcnZG9Gw8v2EyEdBeXAtP/JMxorAqc1ZQpmD8gKHk01eGx9ym6v5gKGbn8FqyAZUfw70kPPNII8G0x4nCPFDCGemRIXbi9OCvsZvnzWbQWP2wnAKUfn0pWmTwG8dPhkHaUiYtGmqS0SHBhtVbAQiCDOM5PcNECEeHeQsY8MJPWo7iO2kcgVQ/PRORtUHbbgyTWSZwZO/7tRLZkMPTMJWfnDfj+ROU02dPu+D8aYEQjk1vVY3hbUHM7Op4gDXmWkHOb/7mwfJi+rTokFX8sX0KgFgjYuULAotnZasL8UXKH3CXbUcHMj/cuBwfpBGlAavtlUcXVZYaGlD362UILL5zMrc4jSRSTCTeL95oq6/YHE8SvL/zcdU6TU9IeMDz4igkiv6Nu/CxjHP9V3EO4okSN2upwbpTv259WnLS8mjMxtTEPevXiG+0EargouqAGRuctDXByskl4HN4L95iLcvtNElorWEODipPWFNu3NhFtSsL9kjv2AXiDH8QIOhKWQX7oVjrUTTrviVFtsWvaD/rz9C1dQ3V55qieScTQ9kImX6fdrBQFov4qwE/e8h3PrUxWS1jxZzQy3RPN4Qei271k2056c0MpmPK/9IwAMrEB2c1IdmCSRjEergpFzCQQ0CN17xH7JoYY=
  file: native-*.tar.gz
  file_glob: true
  skip_cleanup: true
  on:
    repo: y-yagi/crust_json_encoder
    tags: true
after_success: bundle exec rake thermite:tarball
