[package]
name = "rails_json_gem_encoder"
version = "0.0.1"
authors = ["y-yagi <yuuji.yaginuma@gmail.com>"]
edition = "2018"

[lib]
name = "native"
crate-type = ["cdylib"]

[dependencies]
rutie = "0.7.0"
phf = { version = "0.8", features = ["macros"] }
serde_json = "1.0"
