[package]
name = "crust_json_encoder"
version = "0.0.8"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = "0.4"
phf = { version = "0.11", features = ["macros"] }
