name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6.x'
    - name: Install required package
      run: |
        sudo apt-get install libsqlite3-dev
    - name: Install dependencies
      run: |
        gem install bundler --no-document
        bundle install
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: Debug
      run: |
        ruby -e "pp RbConfig::CONFIG['ENABLE_SHARED']"
    - name: Run test
      run: bundle exec rake
